### ISSUE TITLE
Error when creating a four-layer multilayer

### ISSUE THREAD

**Issue by Zhangmochen-zmc** [mnets/pymnet#12]
When I add edges of a single layer using the code like `mnet = MultilayerNetwork(aspects = 3)` and `mnet[1,2,'gene','gene'] = 1`, it reports the error like "KeyError: 'Invalid number of indices.'". But when I change the aspects of the multilayer network to 2 `mnet = MultilayerNetwork(aspects = 2)` and run the same code to add edges, the program runs correctly. So what is the cause of this error?

**Comment by Zhangmochen-zmc** [comment]
Combined with the issue raised in issue5 (https://github.com/bolozna/Multilayer-networks-library/issues/5), I guess the developers set the maximum number of layers to 3 in order to fix the visualization bug.

**Comment by cloner174** [comment]
"Aspect Concept" is not directly related with number of layers. You can set the aspect to 1 and come up with 5 layers, you know!
