### ISSUE TITLE
Seeking help, encountered an error with fig = draw()，how to deal with it?

### ISSUE THREAD

**Issue by Morri2676** [mnets/pymnet#20]
AttributeError                            Traceback (most recent call last)
<ipython-input-26-b3fa52f9c17e> in <module>()
     23 two_layer_net[4, 4, 'a', 'b'] = 1
     24 
---> 25 fig = draw(two_layer_net, layout="circular")
.......
AttributeError: 'NoneType' object has no attribute 'text'

<Figure size 432x288 with 0 Axes>

**Comment by cloner174** [comment]
Hi,
Why Are you using it like that?
Considering how to import the library, you should do one of these:
```python
import pymnet
# And in the some line at the end :
two_layer_net[4, 4, 'a', 'b'] = 1
pymnet.draw(two_layer_net , layout="circle"
```
OR
```python
from pymnet import *
# And in the some line at the end :
two_layer_net[4, 4, 'a', 'b'] = 1
draw(two_layer_net , layout="circle")
```
Be Aware: The option for layout is"circle" , Not 'circlar' !!!

**Comment by ercco** [comment]
Hi, it is not clear where the error is occurring. The error message shows that you're trying to call a method of a `None` object, which I couldn't replicate with the `draw` function. If you want to draw the network into a specific `axes` object, you can use the `ax` parameter of `draw`.
