### ISSUE TITLE
[REVIEW]: Installation instructions in docs/tutorial

### ISSUE THREAD

**Issue by pitmonticone** [mnets/pymnet#22]
In the [docs/tutorial](https://mnets.github.io/pymnet/tutorial/installing.html)
- [x] the mentioned URL to the GitHub repository works, but it is a redirect. Could you update it? 
- [x] the mentioned git clone path is outdated and requires a public SSH key. Could you substitute it with the HTTPS version (i.e. `git clone https://github.com/mnets/pymnet.git`)?

**Comment by dataspider** [comment]
Fixed.
