### ISSUE TITLE
[REVIEW]: Paper title

### ISSUE THREAD

**Issue by pitmonticone** [mnets/pymnet#24]
The current paper title is “`pymnet`: A Multilayer-Networks Library for Python”. 

I believe the hyphen in “Multilayer-Networks” is unnecessary. I suggest removing the hyphen and considering alternative titles such as: 
1. “`pymnet`: A Multilayer Networks Library for Python”
2. “`pymnet`: A Python Library for Multilayer Networks”
3. “`pymnet`: A Multilayer Networks Library in Python”

**Comment by dataspider** [comment]
Thank you for these suggestions! We followed common hyphenation guidelines (e.g., [here](https://www.merriam-webster.com/grammar/hyphen-rules-open-closed-compound-words)) but will still change the title to your second suggestion, which nicely reflects the name of the library.

**Comment by ercco** [comment]
@pitmonticone : As @dataspider mentioned, we have now changed the title to your suggestion number two.
