### ISSUE TITLE
[REVIEW] Improve contribution guide

### ISSUE THREAD

**Issue by nwlandry** [mnets/pymnet#37]
I see that there is a brief contribution guide in the README. It would be helpful to add a few issues with the "Good first issues" (For example, see [NetworkX](https://github.com/networkx/networkx/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22), and link to this label in the contribution section.

In the future, it would be great to make the contribution guide a bit more step-by-step (e.g., fork the repository, make your changes, check test coverage, format code, add docs (is there a docstring format?), make a PR, etc.)

openjournals/joss-reviews#6930

**Comment by arashbm** [comment]
@dataspider I added a simple [HACKING.md](https://github.com/mnets/pymnet/blob/master/HACKING.md) with some of the essentials but will have to add some more information, e.g. formatting commands, code coverage etc.
