### ISSUE TITLE
Plotting a six-layer multilayer

### ISSUE THREAD

**Issue by sofiabaur** [mnets/pymnet#5]
Hi, I'm trying to plot a multilayer with six layers, but I only get 3 and a half layers. I have tried modifying the figsize but the other layers are still blank, although the lab of those layers appears. I would appreciate your help to visualize the whole network.

Also, I would like to know how to set the order of layers.

Thanks for advance.

![image](https://user-images.githubusercontent.com/63755336/158515140-579dd369-d3dd-4166-bbd0-17b4710912be.png)

**Comment by gorostiolam** [comment]
I get the same issue with a 4 layer network, where only 3 layers are visible.

**Comment by cloner174** [comment]
Well this would be a little bit tricky ! But I will guide you as much as I able to.

**Comment by ercco** [comment]
Like @cloner174 said, fitting the layers into the figure depends on the distances between layers (the `layergap` parameter), among other things. You have to experiment with the `draw` parameters to get the layout you want. You can also adjust the `elev` parameter which changes the tilt angle of the layers to fit more layers in the figure.
