### ISSUE TITLE
[REVIEW] Aligning the manuscript with JOSS's standards

### ISSUE THREAD

**Issue by ClaudMor** [mnets/pymnet#50]
Dear Authors,

I would have the following suggestions regarding the draft associated with your submission:

1. The "Summary" section is required to provide an high level overview of the package's functionality and purpose for a non-technical audience. While the purpose has been covered, I don't feel the same for the functionality. Could you extend the Summary to also include the highlights of your package (e.g. the visualization capabilities, the integragion with `bliss`, etc)?
2. The citation style is inconsistent across sections: sometimes papers are cited as [Sallmen et al., 2022](https://academic.oup.com/comnet/article-abstract/10/2/cnac005/6564023?redirectedFrom=fulltext), while others as Kivelä et al. ([2014](https://academic.oup.com/comnet/article/2/3/203/2841130)). Could you make them all the same?
3. The section "Real-World Example" contains the following sentence:

```
In Figure 2, we visualize the data with pymnet, only drawing undirected edges representing aggregate trade volumes of at least one million specimens resp. one thousand kilograms [...]
```

that I suggest changing to

```
In Figure 2, we visualize the data with pymnet, where, with respect to the "live" and "meat" elementary layers of the "trade terms"  aspect, only undirected edges representing aggregate trade volumes of at least one million specimens and one thousand kilograms have been drawn respectively, [...]
```

or other forms that avoid the "resp." abbreviation.

Thank you.

**Comment by dataspider** [comment]
Thank you for your comments and suggestions!
1. I extended the summary accordingly (more precisely: I added one sentence highlighting our highlights as you suggested).
2. The distinction in typesetting is deliberate (one using the markdown syntax with brackets, one using the syntax without brackets), and – unless I missed something – it is actually applied consistently.  
The rule is: `@xyz` (yielding the second style you mentioned) when the citation is used as part of a sentence, `[@xyz]` (yielding the first style you mentioned with round brackets around it). I did identify a redundant semicolon when doing the double-checks, though, which is now fixed.  
I am not a big fan of the difference in linking/coloring either but this is a choice of the rendering template (i.e., not in our control), and the distinction in typesetting seems necessary for smooth readability.
3. Done (I changed "resp." to "or" and simply added ("live") and ("meat") again behind the unit specifications for clarity).

See the updated manuscript [here](https://github.com/openjournals/joss-papers/blob/joss.06930/joss.06930/10.21105.joss.06930.pdf).
